### ISSUE TITLE
Testing - 09

### ISSUE THREAD

**Issue by dpshelio** [UCL-RITS/rsd-classwork-2019#34]
## Separating data from code (10 min)

Your parametrised bit now probably got a bit too big and difficult to read.
Create a `fixture.yaml` file where you can store what you parametrised before
in a more human readable way.

Load the yaml file within the test and use it that structure to feed the parametrize test.

The `fixture.yaml` could look like:
```yaml
- no_overlap:
    test_input:
      time_start: "2019-..."
      time_stop: "2019-..."
    expected:
      ...
- eges:
    ...
```
